services:
  - type: web
    name: be-keuangan
    runtime: node
    plan: free
    autoDeploy: true
    healthCheckPath: /v1/health
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: APP_NAME
        value: be-keuangan
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
